# Generated by Django 4.2.1 on 2023-10-30 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0002_tugatilganboard_bajarilmaganboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TugatilganBoard',
            new_name='BajarilganBoard',
        ),
        migrations.CreateModel(
            name='TugatilmaganBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
